publish:
  docker:
    storage_path: /drone/docker
    when:
      branch: develop
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/simple-html-cd-demo
    file: Dockerfile.staging
    tag: staging
  docker:
    storage_path: /drone/docker
    when:
      branch: [master, release]
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: framgia/simple-html-cd-demo
    file: Dockerfile.production
    tag: latest
deploy:
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_STAGING
    docker_image: framgia/simple-html-cd-demo:staging
    confirm: true
    when:
      branch: develop
  rancher:
    url: $$RANCHER_URL
    access_key: $$RANCHER_ACCESS_KEY
    secret_key: $$RANCHER_SECRET_KEY
    service: $$RANCHER_SERVICE_PRODUCTION
    docker_image: framgia/simple-html-cd-demo:latest
    confirm: true
    when:
      branch: [master, release]
notify:
  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - $$EMAIL_RECIPIENTS
cache:
  mount:
    - /drone/docker
